id: P26EAF001
initial_creation_type: input
source_metadata:
  title: Impermanence Series
  language: en
  description: 'Texts on the subject of impermanence (anitya; mi rtag pa):'
  volume:
    2c9fd5f67ecb4370b7f605d56eb5b0a4:
      title: Verses of Advice for Meditating on Impermanence
      parent: Advice
    cc52b1c680934c00854c48c19c7ac543:
      title: When Flowers Were Ravaged by the Frost
      parent: Songs and Poems
created_at: '2022-03-01T03:58:08.205121'
last_modified_at: '2022-03-01T03:58:08.205127'
